# Titles and introductory text
title: "CpG_Me"
subtitle: "QC for a custom WGBS workflow"
intro_text: "Multiple QC reports summarise filtering, trimming, alignment, and methylation bias (m-bias) results."
report_comment: "This is the LaSalle lab version of CpG_Me for paired end sequencing."

# Report Logo
custom_logo: '/share/lasallelab/programs/CpG_Me/UCDavis.png'
custom_logo_url: 'http://mmi-lab.ucdavis.edu/wordpress/'
custom_logo_title: 'LaSalle Lab @ UC Davis'

#Project level information
report_header_info:
    - Workflow Developer: 'Ben Laufer'
    - E-mail: 'blaufer@ucdavis.edu'
    - Application Type: 'WGBS'
    - Project Type: 'Pilot'
    - Sequencing Platform: 'NovaSeq'
    - Sequencing Setup: 'PE 150 DI'
    - Library Kit: 'Accel-NGS Methyl-Seq (Swift)'
    - Genome: 'hg38'

#extra_fn_clean_exts:
#    - type: regex_keep
#      pattern: '^(.+?)_'

table_columns_visible:
    FastQC (Read 1):
        percent_duplicates: False
        percent_gc: False
        avg_sequence_length: False
        percent_fails: False
        total_sequences: False
    FastQC (Read 2):
        percent_duplicates: False
        percent_gc: False
        avg_sequence_length: False
        percent_fails: False
        total_sequences: False
    Cutadapt:
        percent_trimmed: False
    Bismark:
        dedup_reads: True
        aligned_reads: True

# Reorder    
module_order:
    - fastqc:
        name: 'FastQC (Read 1)'
        info: 'This section of the report shows FastQC results after filtering and adapter trimming.'
        target: ''
        path_filters:
            - '*_1_val_1_fastqc.zip'
    - fastqc:
        name: 'FastQC (Read 2)'
        path_filters:
            - '*_2_val_2_fastqc.zip'
    - cutadapt

remove_sections:
    - fastqc_per_base_sequence_content
    - fastqc_per_base_sequence_content-1

#
# https://github.com/ewels/MultiQC/blob/master/docs/customisation.md
# https://github.com/ewels/MultiQC/issues/542
# https://github.com/ewels/MultiQC/pull/576
